-- Bangladesh-only city and area catalog used by the Tutor registration selector.
-- The upsert makes this migration safe for databases where the catalog was seeded during development.
INSERT INTO `locations` (`id`, `label`, `type`, `country`, `parentId`, `enabled`) VALUES
('tangail-city','Tangail','city','Bangladesh','bd',1),
('sirajganj-city','Sirajগঞ্জ','city','Bangladesh','bd',1),
('dhaka-abdullahpur','Abdullahpur','area','Bangladesh','dhaka-city',1),
('dhaka-adabor','Adabor','area','Bangladesh','dhaka-city',1),
('dhaka-aftabnagar','Aftabnagar','area','Bangladesh','dhaka-city',1),
('dhaka-agargaon','Agargaon','area','Bangladesh','dhaka-city',1),
('dhaka-airport-area','Airport Area','area','Bangladesh','dhaka-city',1),
('dhaka-aram-bagh','Arambagh','area','Bangladesh','dhaka-city',1),
('dhaka-azimpur','Azimpur','area','Bangladesh','dhaka-city',1),
('dhaka-badda','Badda','area','Bangladesh','dhaka-city',1),
('dhaka-baily-road','Baily Road','area','Bangladesh','dhaka-city',1),
('dhaka-banani','Banani','area','Bangladesh','dhaka-city',1),
('dhaka-banani-dohs','Banani DOHS','area','Bangladesh','dhaka-city',1),
('dhaka-banasree','Banasree','area','Bangladesh','dhaka-city',1),
('dhaka-baridhara','Baridhara','area','Bangladesh','dhaka-city',1),
('dhaka-baridhara-dohs','Baridhara DOHS','area','Bangladesh','dhaka-city',1),
('dhaka-bashabo','Bashabo','area','Bangladesh','dhaka-city',1),
('dhaka-bashundhara','Bashundhara R/A','area','Bangladesh','dhaka-city',1),
('dhaka-begun-bari','Begun Bari','area','Bangladesh','dhaka-city',1),
('dhaka-bijoy-sarani','Bijoy Sarani','area','Bangladesh','dhaka-city',1),
('dhaka-bosila','Bosila','area','Bangladesh','dhaka-city',1),
('dhaka-buet-area','BUET Area','area','Bangladesh','dhaka-city',1),
('dhaka-chawk-bazar','Chawk Bazar','area','Bangladesh','dhaka-city',1),
('dhaka-darussalam','Darussalam','area','Bangladesh','dhaka-city',1),
('dhaka-demra','Demra','area','Bangladesh','dhaka-city',1),
('dhaka-dhanmondi','Dhanmondi','area','Bangladesh','dhaka-city',1),
('dhaka-diabari','Diabari','area','Bangladesh','dhaka-city',1),
('dhaka-dilkusha','Dilkusha','area','Bangladesh','dhaka-city',1),
('dhaka-elephant-road','Elephant Road','area','Bangladesh','dhaka-city',1),
('dhaka-farmgate','Farmgate','area','Bangladesh','dhaka-city',1),
('dhaka-gabtoli','Gabtoli','area','Bangladesh','dhaka-city',1),
('dhaka-gulistan','Gulistan','area','Bangladesh','dhaka-city',1),
('dhaka-gulshan-1','Gulshan-1','area','Bangladesh','dhaka-city',1),
('dhaka-gulshan-2','Gulshan-2','area','Bangladesh','dhaka-city',1),
('dhaka-hatirjheel','Hatirjheel','area','Bangladesh','dhaka-city',1),
('dhaka-hazaribagh','Hazaribagh','area','Bangladesh','dhaka-city',1),
('dhaka-jatrabari','Jatrabari','area','Bangladesh','dhaka-city',1),
('dhaka-kakrail','Kakrail','area','Bangladesh','dhaka-city',1),
('dhaka-kalabagan','Kalabagan','area','Bangladesh','dhaka-city',1),
('dhaka-kallyanpur','Kallyanpur','area','Bangladesh','dhaka-city',1),
('dhaka-kamalapur','Kamalapur','area','Bangladesh','dhaka-city',1),
('dhaka-kawran-bazar','Kawran Bazar','area','Bangladesh','dhaka-city',1),
('dhaka-khilgaon','Khilgaon','area','Bangladesh','dhaka-city',1),
('dhaka-khilkhet','Khilkhet','area','Bangladesh','dhaka-city',1),
('dhaka-lalbagh','Lalbagh','area','Bangladesh','dhaka-city',1),
('dhaka-mohakhali','Mohakhali','area','Bangladesh','dhaka-city',1),
('dhaka-mohammadpur','Mohammadpur','area','Bangladesh','dhaka-city',1),
('dhaka-motijheel','Motijheel','area','Bangladesh','dhaka-city',1),
('dhaka-mugda','Mugda','area','Bangladesh','dhaka-city',1),
('dhaka-nakhalpara','Nakhalpara','area','Bangladesh','dhaka-city',1),
('dhaka-pallabi','Pallabi','area','Bangladesh','dhaka-city',1),
('dhaka-panthapath','Panthapath','area','Bangladesh','dhaka-city',1),
('dhaka-puran-dhaka','Puran Dhaka','area','Bangladesh','dhaka-city',1),
('dhaka-ramna','Ramna','area','Bangladesh','dhaka-city',1),
('dhaka-rampura','Rampura','area','Bangladesh','dhaka-city',1),
('dhaka-savar','Savar','area','Bangladesh','dhaka-city',1),
('dhaka-shahbagh','Shahbagh','area','Bangladesh','dhaka-city',1),
('dhaka-shantinagar','Shantinagar','area','Bangladesh','dhaka-city',1),
('dhaka-shyamoli','Shyamoli','area','Bangladesh','dhaka-city',1),
('dhaka-tejgaon','Tejgaon','area','Bangladesh','dhaka-city',1),
('dhaka-uttara','Uttara','area','Bangladesh','dhaka-city',1),
('dhaka-wari','Wari','area','Bangladesh','dhaka-city',1),
('ctg-agrabad','Agrabad','area','Bangladesh','chattogram-city',1),
('ctg-ak-khan','AK Khan','area','Bangladesh','chattogram-city',1),
('ctg-andarkilla','Anderkilla','area','Bangladesh','chattogram-city',1),
('ctg-bahaddarhat','Bahaddarhat','area','Bangladesh','chattogram-city',1),
('ctg-bayezid','Bayezid','area','Bangladesh','chattogram-city',1),
('ctg-chawkbazar','Chawkbazar','area','Bangladesh','chattogram-city',1),
('ctg-gec','GEC Circle','area','Bangladesh','chattogram-city',1),
('ctg-halishahar','Halishahar','area','Bangladesh','chattogram-city',1),
('ctg-jamal-khan','Jamal Khan','area','Bangladesh','chattogram-city',1),
('ctg-khulshi','Khulshi','area','Bangladesh','chattogram-city',1),
('ctg-lalkhan-bazar','Lalkhan Bazar','area','Bangladesh','chattogram-city',1),
('ctg-muradpur','Muradpur','area','Bangladesh','chattogram-city',1),
('ctg-nasirabad','Nasirabad','area','Bangladesh','chattogram-city',1),
('ctg-panchlaish','Panchlaish','area','Bangladesh','chattogram-city',1),
('ctg-pahartali','Pahartali','area','Bangladesh','chattogram-city',1),
('ctg-patenga','Patenga','area','Bangladesh','chattogram-city',1),
('ctg-port','Port','area','Bangladesh','chattogram-city',1),
('ctg-tigerpass','Tigerpass','area','Bangladesh','chattogram-city',1),
('sylhet-ambarkhana','Ambarkhana','area','Bangladesh','sylhet-city',1),
('sylhet-bandar-bazar','Bandar Bazar','area','Bangladesh','sylhet-city',1),
('sylhet-dargah-gate','Dargah Gate','area','Bangladesh','sylhet-city',1),
('sylhet-kazir-bazar','Kazir Bazar','area','Bangladesh','sylhet-city',1),
('sylhet-madina-market','Madina Market','area','Bangladesh','sylhet-city',1),
('sylhet-mirabazar','Mirabazar','area','Bangladesh','sylhet-city',1),
('sylhet-shahjalal-upashahar','Shahjalal Upashahar','area','Bangladesh','sylhet-city',1),
('sylhet-shibgonj','Shibgonj','area','Bangladesh','sylhet-city',1),
('sylhet-subid-bazar','Subid Bazar','area','Bangladesh','sylhet-city',1),
('sylhet-tilagor','Tilagor','area','Bangladesh','sylhet-city',1),
('sylhet-zindabazar','Zindabazar','area','Bangladesh','sylhet-city',1),
('raj-boalia','Boalia','area','Bangladesh','rajshahi-city',1),
('raj-binodpur','Binodpur','area','Bangladesh','rajshahi-city',1),
('raj-katakhali','Katakhali','area','Bangladesh','rajshahi-city',1),
('raj-kazla','Kazla','area','Bangladesh','rajshahi-city',1),
('raj-laxmipur','Laxmipur','area','Bangladesh','rajshahi-city',1),
('raj-motihar','Motihar','area','Bangladesh','rajshahi-city',1),
('raj-rajpara','Rajpara','area','Bangladesh','rajshahi-city',1),
('raj-shaheb-bazar','Shaheb Bazar','area','Bangladesh','rajshahi-city',1),
('raj-shiroil','Shiroil','area','Bangladesh','rajshahi-city',1),
('raj-sopura','Sopura','area','Bangladesh','rajshahi-city',1),
('raj-talaimari','Talaimari','area','Bangladesh','rajshahi-city',1),
('raj-upashahar','Upashahar','area','Bangladesh','rajshahi-city',1),
('khulna-boyra','Boyra','area','Bangladesh','khulna-city',1),
('khulna-daulatpur','Daulatpur','area','Bangladesh','khulna-city',1),
('khulna-gollamari','Gollamari','area','Bangladesh','khulna-city',1),
('khulna-khalishpur','Khalishpur','area','Bangladesh','khulna-city',1),
('khulna-sadar','Khulna Sadar','area','Bangladesh','khulna-city',1),
('khulna-mujgunni','Mujgunni','area','Bangladesh','khulna-city',1),
('khulna-nirala','Nirala','area','Bangladesh','khulna-city',1),
('khulna-rupsha','Rupsha','area','Bangladesh','khulna-city',1),
('khulna-shib-bari','Shib Bari','area','Bangladesh','khulna-city',1),
('khulna-sonadanga','Sonadanga','area','Bangladesh','khulna-city',1),
('khulna-tutpara','Tutpara','area','Bangladesh','khulna-city',1),
('barishal-alekanda','Alekanda','area','Bangladesh','barishal-city',1),
('barishal-bogura-road','Bogura Road','area','Bangladesh','barishal-city',1),
('barishal-cb-road','C&B Road','area','Bangladesh','barishal-city',1),
('barishal-chawkbazar','Chawkbazar','area','Bangladesh','barishal-city',1),
('barishal-kashipur','Kashipur','area','Bangladesh','barishal-city',1),
('barishal-kawnia','Kawnia','area','Bangladesh','barishal-city',1),
('barishal-nathullabad','Nathullabad','area','Bangladesh','barishal-city',1),
('barishal-rupatali','Rupatali','area','Bangladesh','barishal-city',1),
('barishal-sadar-road','Sadar Road','area','Bangladesh','barishal-city',1),
('barishal-sagardi','Sagardi','area','Bangladesh','barishal-city',1),
('rangpur-co-bazar','CO Bazar','area','Bangladesh','rangpur-city',1),
('rangpur-dhap','Dhap','area','Bangladesh','rangpur-city',1),
('rangpur-kamarpara','Kamarpara','area','Bangladesh','rangpur-city',1),
('rangpur-lalbagh','Lalbagh','area','Bangladesh','rangpur-city',1),
('rangpur-mahiganj','Mahiganj','area','Bangladesh','rangpur-city',1),
('rangpur-medical-mor','Medical Mor','area','Bangladesh','rangpur-city',1),
('rangpur-modern-mor','Modern Mor','area','Bangladesh','rangpur-city',1),
('rangpur-sadar','Rangpur Sadar','area','Bangladesh','rangpur-city',1),
('rangpur-shapla-chattar','Shapla Chattar','area','Bangladesh','rangpur-city',1),
('rangpur-station-road','Station Road','area','Bangladesh','rangpur-city',1),
('mymensingh-akua','Akua','area','Bangladesh','mymensingh-city',1),
('mymensingh-boro-bazar','Boro Bazar','area','Bangladesh','mymensingh-city',1),
('mymensingh-charpara','Charpara','area','Bangladesh','mymensingh-city',1),
('mymensingh-ganginarpar','Ganginarpar','area','Bangladesh','mymensingh-city',1),
('mymensingh-kachijhuli','Kachijhuli','area','Bangladesh','mymensingh-city',1),
('mymensingh-maskanda','Maskanda','area','Bangladesh','mymensingh-city',1),
('mymensingh-sadar','Mymensingh Sadar','area','Bangladesh','mymensingh-city',1),
('mymensingh-shambhuganj','Shambhuganj','area','Bangladesh','mymensingh-city',1),
('mymensingh-town-hall','Town Hall','area','Bangladesh','mymensingh-city',1),
('tangail-akur-takur','Akur Takur','area','Bangladesh','tangail-city',1),
('tangail-baghil','Baghil','area','Bangladesh','tangail-city',1),
('tangail-bepari-para','Bepari Para','area','Bangladesh','tangail-city',1),
('tangail-college-gate','College Gate','area','Bangladesh','tangail-city',1),
('tangail-kagmara','Kagmara','area','Bangladesh','tangail-city',1),
('tangail-new-market','New Market','area','Bangladesh','tangail-city',1),
('tangail-sabalia','Sabalia','area','Bangladesh','tangail-city',1),
('tangail-santosh','Santosh','area','Bangladesh','tangail-city',1),
('tangail-sadar','Tangail Sadar','area','Bangladesh','tangail-city',1),
('tangail-thana-para','Thana Para','area','Bangladesh','tangail-city',1),
('sirajganj-bagbari','Bagbari','area','Bangladesh','sirajganj-city',1),
('sirajganj-bazar-station','Bazar Station Road','area','Bangladesh','sirajganj-city',1),
('sirajganj-belkuichi-road','Belkuchi Road','area','Bangladesh','sirajganj-city',1),
('sirajganj-dhaka-road','Dhaka Road','area','Bangladesh','sirajganj-city',1),
('sirajganj-kalia-haripur','Kalia Haripur','area','Bangladesh','sirajganj-city',1),
('sirajganj-railgate','Railgate','area','Bangladesh','sirajganj-city',1),
('sirajganj-sadar','Sirajগঞ্জ Sadar','area','Bangladesh','sirajganj-city',1),
('sirajganj-shialkol','Shialkol','area','Bangladesh','sirajganj-city',1),
('sirajganj-ss-road','SS Road','area','Bangladesh','sirajganj-city',1)
ON DUPLICATE KEY UPDATE
  `label` = VALUES(`label`),
  `type` = VALUES(`type`),
  `country` = VALUES(`country`),
  `parentId` = VALUES(`parentId`),
  `enabled` = VALUES(`enabled`);
