-- Derived only from the user-provided Bangladesh location structure; additive and idempotent.
-- The parent-capable locations table keeps existing saved Tutor Profile location IDs valid.

INSERT INTO locations (id, label, type, country, parentId, enabled) VALUES
  ('dhaka-city', 'Dhaka', 'city', 'Bangladesh', 'bd', 1),
  ('chattogram-city', 'Chattogram', 'city', 'Bangladesh', 'bd', 1),
  ('rajshahi-city', 'Rajshahi', 'city', 'Bangladesh', 'bd', 1),
  ('khulna-city', 'Khulna', 'city', 'Bangladesh', 'bd', 1),
  ('barishal-city', 'Barishal', 'city', 'Bangladesh', 'bd', 1),
  ('sylhet-city', 'Sylhet', 'city', 'Bangladesh', 'bd', 1),
  ('rangpur-city', 'Rangpur', 'city', 'Bangladesh', 'bd', 1),
  ('mymensingh-city', 'Mymensingh', 'city', 'Bangladesh', 'bd', 1),
  ('cumilla-district', 'Cumilla', 'district', 'Bangladesh', 'bd', 1),
  ('gazipur-district', 'Gazipur', 'district', 'Bangladesh', 'bd', 1),
  ('narayanganj-district', 'Narayanganj', 'district', 'Bangladesh', 'bd', 1),
  ('tangail-city', 'Tangail', 'city', 'Bangladesh', 'bd', 1),
  ('sirajganj-city', 'Sirajganj', 'city', 'Bangladesh', 'bd', 1),
  ('dhaka-thana-adabar', 'Adabar', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-agargaon', 'Agargaon', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-badda', 'Badda', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-bangshal', 'Bangshal', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-cantonment', 'Cantonment', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-chawk-bazar', 'Chawk Bazar', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-dhanmondi', 'Dhanmondi', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-demra', 'Demra', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-gulshan', 'Gulshan', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-hazaribagh', 'Hazaribagh', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-hatirjheel', 'Hatirjheel', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-jatrabari', 'Jatrabari', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-kadamtali', 'Kadamtali', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-kafrul', 'Kafrul', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-kalabagan', 'Kalabagan', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-kamrangirchar', 'Kamrangirchar', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-khilgaon', 'Khilgaon', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-khilkhet', 'Khilkhet', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-kotwali', 'Kotwali', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-lalbagh', 'Lalbagh', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-mirpur', 'Mirpur', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-mohammadpur', 'Mohammadpur', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-motijheel', 'Motijheel', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-mugda', 'Mugda', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-new-market', 'New Market', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-pallabi', 'Pallabi', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-paltan', 'Paltan', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-ramna', 'Ramna', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-sabujbagh', 'Sabujbagh', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-shah-ali', 'Shah Ali', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-shahjahanpur', 'Shahjahanpur', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-sher-e-bangla-nagar', 'Sher-e-Bangla Nagar', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-shyampur', 'Shyampur', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-sutrapur', 'Sutrapur', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-tejgaon', 'Tejgaon', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-tejgaon-industrial-area', 'Tejgaon Industrial Area', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-turag', 'Turag', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-uttara', 'Uttara', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-vatara', 'Vatara', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-thana-wari', 'Wari', 'thana', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-farmgate', 'Farmgate', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-kawran-bazar', 'Kawran Bazar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-gulshan-1', 'Gulshan-1', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-gulshan-2', 'Gulshan-2', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-gulshan-avenue', 'Gulshan Avenue', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-banani', 'Banani', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-baridhara', 'Baridhara', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-diplomatic-zone', 'Diplomatic Zone', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-bashundhara-r-a-block-a-n', 'Bashundhara R/A (Block A–N)', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-bashundhara-residential', 'Bashundhara Residential', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-motijheel', 'Motijheel', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-bijoynagar', 'Bijoynagar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-dhanmondi', 'Dhanmondi', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-mohammadpur', 'Mohammadpur', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-shyamoli', 'Shyamoli', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-azimpur', 'Azimpur', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-new-market', 'New Market', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-panthapath', 'Panthapath', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-hatirpool', 'Hatirpool', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-malibagh', 'Malibagh', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-khilgaon', 'Khilgaon', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-badda', 'Badda', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-vatara', 'Vatara', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-khilkhet', 'Khilkhet', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-kuril', 'Kuril', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-rampura', 'Rampura', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-mogbazar', 'Mogbazar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-shantinagar', 'Shantinagar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-kakrail', 'Kakrail', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-wari', 'Wari', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-old-dhaka', 'Old Dhaka', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-chawk-bazar', 'Chawk Bazar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-lalbagh', 'Lalbagh', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-jatrabari', 'Jatrabari', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-demra', 'Demra', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-mugda', 'Mugda', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-sabujbagh', 'Sabujbagh', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-kamrangirchar', 'Kamrangirchar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-rayer-bazar', 'Rayer Bazar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-tejgaon-industrial-area', 'Tejgaon Industrial Area', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-savar', 'Savar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-aminbazar', 'Aminbazar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-baipayl', 'Baipayl', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-hemayetpur', 'Hemayetpur', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-dhamrai', 'Dhamrai', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-dohar', 'Dohar', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-keraniganj', 'Keraniganj', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-nawabganj', 'Nawabganj', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-gazipur-border', 'Gazipur Border', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-ashulia', 'Ashulia', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-area-tongi', 'Tongi', 'area', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-upazila-dhamrai', 'Dhamrai', 'upazila', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-upazila-dohar', 'Dohar', 'upazila', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-upazila-keraniganj', 'Keraniganj', 'upazila', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-upazila-nawabganj', 'Nawabganj', 'upazila', 'Bangladesh', 'dhaka-city', 1),
  ('dhaka-upazila-savar', 'Savar', 'upazila', 'Bangladesh', 'dhaka-city', 1),
  ('chattogram-thana-akbarshah', 'Akbarshah', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-bakalia', 'Bakalia', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-bandar', 'Bandar', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-bayazid', 'Bayazid', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-bhujpur', 'Bhujpur', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-chandgaon', 'Chandgaon', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-chawkbazar', 'Chawkbazar', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-double-mooring', 'Double Mooring', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-epz', 'EPZ', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-halishahar', 'Halishahar', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-khulshi', 'Khulshi', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-kotwali', 'Kotwali', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-pahartali', 'Pahartali', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-panchlaish', 'Panchlaish', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-patenga', 'Patenga', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-thana-sadarghat', 'Sadarghat', 'thana', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-gec-circle', 'GEC Circle', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-chawk-bazar-circle', 'Chawk Bazar Circle', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-agrabad', 'Agrabad', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-pathantuli', 'Pathantuli', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-gosaildanga', 'Gosaildanga', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-nasirabad', 'Nasirabad', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-khulshi-r-a', 'Khulshi R/A', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-panchlaish-r-a', 'Panchlaish R/A', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-chandgaon-r-a', 'Chandgaon R/A', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-halishahar-r-a', 'Halishahar R/A', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-muradpur', 'Muradpur', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-sholashahar', 'Sholashahar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-mohra', 'Mohra', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-bishwa-road', 'Bishwa Road', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-tiger-pass', 'Tiger Pass', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-jaldia', 'Jaldia', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-pahartali', 'Pahartali', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-lalkhan-bazar', 'Lalkhan Bazar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-kattali', 'Kattali', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-jalalabad', 'Jalalabad', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-aman-shah', 'Aman Shah', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-saraipara', 'Saraipara', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-jamal-khan', 'Jamal Khan', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-dewan-bazar', 'Dewan Bazar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-enayet-bazar', 'Enayet Bazar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-andarkilla', 'Andarkilla', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-firingee-bazar', 'Firingee Bazar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-patharghata', 'Patharghata', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-alkaran', 'Alkaran', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-nawabpur', 'Nawabpur', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-madarbari', 'Madarbari', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-baddarhat', 'Baddarhat', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-bakhshirhat', 'Bakhshirhat', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-patenga', 'Patenga', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-patenga-beach', 'Patenga Beach', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-shah-amanat-airport', 'Shah Amanat Airport', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-anandabazar', 'Anandabazar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-bay-terminal', 'Bay Terminal', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-bandar', 'Bandar', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-sadarghat', 'Sadarghat', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-kalurghat', 'Kalurghat', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-chaktai', 'Chaktai', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-area-akbarshah', 'Akbarshah', 'area', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-anwara', 'Anwara', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-banshkhali', 'Banshkhali', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-boalkhali', 'Boalkhali', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-chandanaish', 'Chandanaish', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-fatikchhari', 'Fatikchhari', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-fatikchhari-north', 'Fatikchhari North', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-hathazari', 'Hathazari', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-karnaphuli', 'Karnaphuli', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-lohagara', 'Lohagara', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-mirsharai', 'Mirsharai', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-patiya', 'Patiya', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-rangunia', 'Rangunia', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-raozan', 'Raozan', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-sandwip', 'Sandwip', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-satkania', 'Satkania', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('chattogram-upazila-sitakunda', 'Sitakunda', 'upazila', 'Bangladesh', 'chattogram-city', 1),
  ('rajshahi-thana-boalia', 'Boalia', 'thana', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-thana-matihar', 'Matihar', 'thana', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-thana-rajpara', 'Rajpara', 'thana', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-thana-shah-makhdum', 'Shah Makhdum', 'thana', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-shaheb-bazar', 'Shaheb Bazar', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-court-more', 'Court More', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-talaimari', 'Talaimari', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-hararganj', 'Hararganj', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-uposhohor', 'Uposhohor', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-kazla', 'Kazla', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-dorgapara', 'Dorgapara', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-katakhali', 'Katakhali', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-shibganj', 'Shibganj', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-binnati-more', 'Binnati More', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-padma-garden', 'Padma Garden', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-ghoramara', 'Ghoramara', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-natore-road', 'Natore Road', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-dhepa-epz', 'Dhepa EPZ', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-rajshahi-university', 'Rajshahi University', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-new-market', 'New Market', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-lalkuthi', 'Lalkuthi', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-gopalpur-road', 'Gopalpur Road', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-dhepurhat', 'Dhepurhat', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-bagha', 'Bagha', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-bagmara', 'Bagmara', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-charghat', 'Charghat', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-durgapur', 'Durgapur', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-godagari', 'Godagari', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-mohanpur', 'Mohanpur', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-paba', 'Paba', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-puthia', 'Puthia', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-area-tanore', 'Tanore', 'area', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-bagha', 'Bagha', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-bagmara', 'Bagmara', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-charghat', 'Charghat', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-durgapur', 'Durgapur', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-godagari', 'Godagari', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-mohanpur', 'Mohanpur', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-paba', 'Paba', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-puthia', 'Puthia', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('rajshahi-upazila-tanore', 'Tanore', 'upazila', 'Bangladesh', 'rajshahi-city', 1),
  ('khulna-thana-daulatpur', 'Daulatpur', 'thana', 'Bangladesh', 'khulna-city', 1),
  ('khulna-thana-khalishpur', 'Khalishpur', 'thana', 'Bangladesh', 'khulna-city', 1),
  ('khulna-thana-khan-jahan-ali', 'Khan Jahan Ali', 'thana', 'Bangladesh', 'khulna-city', 1),
  ('khulna-thana-kotwali', 'Kotwali', 'thana', 'Bangladesh', 'khulna-city', 1),
  ('khulna-thana-sonadanga', 'Sonadanga', 'thana', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-sonadanga', 'Sonadanga', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-sonadanga-r-a', 'Sonadanga R/A', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-khalishpur', 'Khalishpur', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-khalishpur-r-a', 'Khalishpur R/A', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-daulatpur', 'Daulatpur', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-shibbari', 'Shibbari', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-boyra', 'Boyra', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-fullbarigate', 'Fullbarigate', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-nirala', 'Nirala', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-gollamari', 'Gollamari', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-majher-char', 'Majher Char', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-rupsha', 'Rupsha', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-khulna-railway-station', 'Khulna Railway Station', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-kda-avenue', 'KDA Avenue', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-chittaranjan-avenue', 'Chittaranjan Avenue', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-khulna-epz', 'Khulna EPZ', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-shiromoni', 'Shiromoni', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-rupsha-bridge', 'Rupsha Bridge', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-mayur-river', 'Mayur River', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-batiaghata', 'Batiaghata', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-dacope', 'Dacope', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-dighalia', 'Dighalia', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-dumuria', 'Dumuria', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-koyra', 'Koyra', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-paikgachha', 'Paikgachha', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-phultala', 'Phultala', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-rupsa', 'Rupsa', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-area-terokhada', 'Terokhada', 'area', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-batiaghata', 'Batiaghata', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-dacope', 'Dacope', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-dighalia', 'Dighalia', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-dumuria', 'Dumuria', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-koyra', 'Koyra', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-paikgachha', 'Paikgachha', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-phultala', 'Phultala', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-rupsa', 'Rupsa', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('khulna-upazila-terokhada', 'Terokhada', 'upazila', 'Bangladesh', 'khulna-city', 1),
  ('barishal-thana-barishal-kotwali', 'Barishal Kotwali', 'thana', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-bandar-road', 'Bandar Road', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-rupatali', 'Rupatali', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-bell-s-park', 'Bell''s Park', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-candb-road', 'C&B Road', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-kawnia', 'Kawnia', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-chawk-bazar', 'Chawk Bazar', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-college-road', 'College Road', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-nabagram', 'Nabagram', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-bibir-char', 'Bibir Char', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-chandrima-uddan', 'Chandrima Uddan', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-roysheen', 'Roysheen', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-gorakhali', 'Gorakhali', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-amtola', 'Amtola', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-barishal-river-port', 'Barishal River Port', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-agailjhara', 'Agailjhara', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-babuganj', 'Babuganj', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-bakerganj', 'Bakerganj', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-banaripara', 'Banaripara', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-gournadi', 'Gournadi', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-hizla', 'Hizla', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-mehendiganj', 'Mehendiganj', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-muladi', 'Muladi', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-area-wazirpur', 'Wazirpur', 'area', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-agailjhara', 'Agailjhara', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-babuganj', 'Babuganj', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-bakerganj', 'Bakerganj', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-banaripara', 'Banaripara', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-barisal-sadar', 'Barisal Sadar', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-gournadi', 'Gournadi', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-hizla', 'Hizla', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-mehendiganj', 'Mehendiganj', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-muladi', 'Muladi', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('barishal-upazila-wazirpur', 'Wazirpur', 'upazila', 'Bangladesh', 'barishal-city', 1),
  ('sylhet-thana-biman-bandar', 'Biman Bandar', 'thana', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-thana-jalalabad', 'Jalalabad', 'thana', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-thana-kotwali', 'Kotwali', 'thana', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-thana-shahjalal', 'Shahjalal', 'thana', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-zindabazar', 'Zindabazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-chowhatta', 'Chowhatta', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-ambarkhana', 'Ambarkhana', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-bandar-bazar', 'Bandar Bazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-tilagarh', 'Tilagarh', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-tilagarh-r-a', 'Tilagarh R/A', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-surma', 'Surma', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-surma-r-a', 'Surma R/A', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-kumarpara', 'Kumarpara', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-pathantula', 'Pathantula', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-shibganj', 'Shibganj', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-rakkhiya-bazar', 'Rakkhiya Bazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-uposhahar', 'Uposhahar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-dargah-gate', 'Dargah Gate', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-east-dargah', 'East Dargah', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-west-dargah', 'West Dargah', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-kazi-bazar', 'Kazi Bazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-bhatipara', 'Bhatipara', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-shimulbag', 'Shimulbag', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-osmani-nagar', 'Osmani Nagar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-lala-bazar', 'Lala Bazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-hazrat-shahjalal', 'Hazrat Shahjalal', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-balaganj', 'Balaganj', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-beanibazar', 'Beanibazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-bishwanath', 'Bishwanath', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-companiganj', 'Companiganj', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-dakshin-surma', 'Dakshin Surma', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-fenchuganj', 'Fenchuganj', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-golapganj', 'Golapganj', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-gowainghat', 'Gowainghat', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-jaflong', 'Jaflong', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-jaintiapur', 'Jaintiapur', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-kanaighat', 'Kanaighat', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-zakiganj', 'Zakiganj', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-area-moglabazar', 'Moglabazar', 'area', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-balaganj', 'Balaganj', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-beanibazar', 'Beanibazar', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-bishwanath', 'Bishwanath', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-companiganj', 'Companiganj', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-dakshin-surma', 'Dakshin Surma', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-fenchuganj', 'Fenchuganj', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-golapganj', 'Golapganj', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-gowainghat', 'Gowainghat', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-jaintiapur', 'Jaintiapur', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-kanaighat', 'Kanaighat', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-osmani-nagar', 'Osmani Nagar', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-sylhet-sadar', 'Sylhet Sadar', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('sylhet-upazila-zakiganj', 'Zakiganj', 'upazila', 'Bangladesh', 'sylhet-city', 1),
  ('rangpur-area-tajhat', 'Tajhat', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-mahiganj', 'Mahiganj', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-carmichael-road', 'Carmichael Road', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-town-hall', 'Town Hall', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-jail-road', 'Jail Road', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-modern-mor', 'Modern Mor', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-boro-alamnagar', 'Boro Alamnagar', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-college-para', 'College Para', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-satmatha', 'Satmatha', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-beldanga', 'Beldanga', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-station-road', 'Station Road', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-mahiganj-epz', 'Mahiganj EPZ', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-badarganj', 'Badarganj', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-mithapukur', 'Mithapukur', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-gangachhara', 'Gangachhara', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-kaunia', 'Kaunia', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-pirgacha', 'Pirgacha', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-pirganj', 'Pirganj', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-taraganj', 'Taraganj', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-payra-bondor', 'Payra Bondor', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-area-gopigonj', 'Gopigonj', 'area', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-badarganj', 'Badarganj', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-mithapukur', 'Mithapukur', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-gangachhara', 'Gangachhara', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-kaunia', 'Kaunia', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-rangpur-sadar', 'Rangpur Sadar', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-pirgacha', 'Pirgacha', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-pirganj', 'Pirganj', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('rangpur-upazila-taraganj', 'Taraganj', 'upazila', 'Bangladesh', 'rangpur-city', 1),
  ('mymensingh-area-akua', 'Akua', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-charpara', 'Charpara', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-nandipur', 'Nandipur', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-ganginar-par', 'Ganginar Par', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-bagmara', 'Bagmara', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-shombhuganj', 'Shombhuganj', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-boro-bazar', 'Boro Bazar', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-kewatkhali', 'Kewatkhali', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-college-road', 'College Road', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-railway-station-area', 'Railway Station Area', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-char-ishwardia', 'Char Ishwardia', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-notun-bazar', 'Notun Bazar', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-mymensingh-epz', 'Mymensingh EPZ', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-bhaluka-epz', 'Bhaluka EPZ', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-bhaluka', 'Bhaluka', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-dhobaura', 'Dhobaura', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-fulbaria', 'Fulbaria', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-gaffargaon', 'Gaffargaon', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-gauripur', 'Gauripur', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-haluaghat', 'Haluaghat', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-ishwarganj', 'Ishwarganj', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-mymensingh-sadar', 'Mymensingh Sadar', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-muktagachha', 'Muktagachha', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-nandail', 'Nandail', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-phulpur', 'Phulpur', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-trishal', 'Trishal', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-goshaidanga', 'Goshaidanga', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-area-baniani', 'Baniani', 'area', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-bhaluka', 'Bhaluka', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-dhobaura', 'Dhobaura', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-fulbaria', 'Fulbaria', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-gaffargaon', 'Gaffargaon', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-gauripur', 'Gauripur', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-haluaghat', 'Haluaghat', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-ishwarganj', 'Ishwarganj', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-mymensingh-sadar', 'Mymensingh Sadar', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-muktagachha', 'Muktagachha', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-nandail', 'Nandail', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-phulpur', 'Phulpur', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('mymensingh-upazila-trishal', 'Trishal', 'upazila', 'Bangladesh', 'mymensingh-city', 1),
  ('cumilla-area-kandirpar', 'Kandirpar', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-court-bazar', 'Court Bazar', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-naya-bazar', 'Naya Bazar', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-shimaibag', 'Shimaibag', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-jhautola', 'Jhautola', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-rajgonj', 'Rajgonj', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-lalmatir-more', 'Lalmatir More', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-station-road', 'Station Road', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-cumilla-cantonment', 'Cumilla Cantonment', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-kotbari', 'Kotbari', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-mainamati', 'Mainamati', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-mainamoti', 'Mainamoti', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-bard', 'BARD', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-bibi-bazar-land-port', 'Bibi Bazar (Land Port)', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-hosen-shah-road', 'Hosen Shah Road', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-akhaura-road', 'Akhaura Road', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-dharmasagar', 'Dharmasagar', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-area-gomia', 'Gomia', 'area', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-barura', 'Barura', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-brahmanpara', 'Brahmanpara', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-burichong', 'Burichong', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-chandina', 'Chandina', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-chauddagram', 'Chauddagram', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-cumilla-adarsha-sadar', 'Cumilla Adarsha Sadar', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-cumilla-sadar-dakshin', 'Cumilla Sadar Dakshin', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-daudkandi', 'Daudkandi', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-debidwar', 'Debidwar', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-homna', 'Homna', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-laksam', 'Laksam', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-meghna', 'Meghna', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-monohorgonj', 'Monohorgonj', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-muradnagar', 'Muradnagar', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-nangalkot', 'Nangalkot', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('cumilla-upazila-titas', 'Titas', 'upazila', 'Bangladesh', 'cumilla-district', 1),
  ('gazipur-area-tongi', 'Tongi', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-joydebpur', 'Joydebpur', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-konabari', 'Konabari', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-kashem-bazar', 'Kashem Bazar', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-tongi-industrial-area', 'Tongi Industrial Area', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-salna', 'Salna', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-chourasta', 'Chourasta', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-board-bazar', 'Board Bazar', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-pirujali', 'Pirujali', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-rajendrapur-cantonment', 'Rajendrapur Cantonment', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-bscic-industrial-area', 'BSCIC Industrial Area', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-kaliakair', 'Kaliakair', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-hi-tech-city-kaliakair', 'Hi-Tech City Kaliakair', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-harashpur', 'Harashpur', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-baipayl', 'Baipayl', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-kaliganj', 'Kaliganj', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-kapasia', 'Kapasia', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-sreepur', 'Sreepur', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-maona-chowrasta', 'Maona Chowrasta', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-bhawal-national-park', 'Bhawal National Park', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-bhawal-rajbari', 'Bhawal Rajbari', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-gazipur-safari-park', 'Gazipur Safari Park', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-bishwa-ijtema-ground-tongi', 'Bishwa Ijtema Ground (Tongi)', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-duet-area', 'DUET Area', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-iut-area', 'IUT Area', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-ekdala', 'Ekdala', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-area-bakhtarpur', 'Bakhtarpur', 'area', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-upazila-gazipur-sadar', 'Gazipur Sadar', 'upazila', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-upazila-kaliakair', 'Kaliakair', 'upazila', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-upazila-kaliganj', 'Kaliganj', 'upazila', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-upazila-kapasia', 'Kapasia', 'upazila', 'Bangladesh', 'gazipur-district', 1),
  ('gazipur-upazila-sreepur', 'Sreepur', 'upazila', 'Bangladesh', 'gazipur-district', 1),
  ('narayanganj-area-gobra', 'Gobra', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-fatulla', 'Fatulla', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-nabiganj', 'Nabiganj', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-taltola', 'Taltola', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-siddhirganj', 'Siddhirganj', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-adamjee-epz', 'Adamjee EPZ', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-narayanganj-epz', 'Narayanganj EPZ', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-kalur-bazar', 'Kalur Bazar', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-boro-bazar', 'Boro Bazar', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-hakim-para', 'Hakim Para', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-kadam-rasul', 'Kadam Rasul', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-chashara', 'Chashara', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-lanchpur', 'Lanchpur', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-murapara', 'Murapara', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-bhulta', 'Bhulta', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-kanchan', 'Kanchan', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-panam-nagar', 'Panam Nagar', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-mograpara', 'Mograpara', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-baradi', 'Baradi', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-araihazar', 'Araihazar', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-rupganj', 'Rupganj', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-bandar', 'Bandar', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-area-sonargaon', 'Sonargaon', 'area', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-upazila-araihazar', 'Araihazar', 'upazila', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-upazila-bandar', 'Bandar', 'upazila', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-upazila-narayanganj-sadar', 'Narayanganj Sadar', 'upazila', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-upazila-rupganj', 'Rupganj', 'upazila', 'Bangladesh', 'narayanganj-district', 1),
  ('narayanganj-upazila-sonargaon', 'Sonargaon', 'upazila', 'Bangladesh', 'narayanganj-district', 1),
  ('tangail-area-tangail-sadar', 'Tangail Sadar', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-elenga', 'Elenga', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-korotia', 'Korotia', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-kalabari', 'Kalabari', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-college-road', 'College Road', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-ghatail', 'Ghatail', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-safari-park-ghatail', 'Safari Park Ghatail', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-madhupur', 'Madhupur', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-pakutia', 'Pakutia', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-mohera', 'Mohera', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-kabilapara', 'Kabilapara', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-pathrail', 'Pathrail', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-basail', 'Basail', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-mirzapur', 'Mirzapur', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-kalihati', 'Kalihati', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-bangabandhu-jamuna-bridge-bhuapur', 'Bangabandhu Jamuna Bridge (Bhuapur)', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-delduar', 'Delduar', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-nagarpur', 'Nagarpur', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-sakhipur', 'Sakhipur', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-gopalpur', 'Gopalpur', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-dhanbari', 'Dhanbari', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-area-bhuapur', 'Bhuapur', 'area', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-basail', 'Basail', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-bhuapur', 'Bhuapur', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-delduar', 'Delduar', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-dhanbari', 'Dhanbari', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-ghatail', 'Ghatail', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-gopalpur', 'Gopalpur', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-kalihati', 'Kalihati', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-madhupur', 'Madhupur', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-mirzapur', 'Mirzapur', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-nagarpur', 'Nagarpur', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-sakhipur', 'Sakhipur', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('tangail-upazila-tangail-sadar', 'Tangail Sadar', 'upazila', 'Bangladesh', 'tangail-city', 1),
  ('sirajganj-area-sirajganj-sadar', 'Sirajganj Sadar', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-hard-point', 'Hard Point', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-china', 'China', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-rail-bazar', 'Rail Bazar', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-college-road', 'College Road', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-court-more', 'Court More', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-shahjadpur', 'Shahjadpur', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-porjana', 'Porjana', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-kamarkhanda', 'Kamarkhanda', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-kazipur', 'Kazipur', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-belkuchi', 'Belkuchi', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-enayetpur', 'Enayetpur', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-tarash', 'Tarash', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-chalan-beel', 'Chalan Beel', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-nagarbari', 'Nagarbari', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-jamuna-bridge-sirajganj', 'Jamuna Bridge (Sirajganj)', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-raiganj', 'Raiganj', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-sirajganj-economic-zone', 'Sirajganj Economic Zone', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-ullahpara', 'Ullahpara', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-area-chauhali', 'Chauhali', 'area', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-belkuchi', 'Belkuchi', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-chauhali', 'Chauhali', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-kamarkhanda', 'Kamarkhanda', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-kazipur', 'Kazipur', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-raiganj', 'Raiganj', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-shahjadpur', 'Shahjadpur', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-sirajganj-sadar', 'Sirajganj Sadar', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-tarash', 'Tarash', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('sirajganj-upazila-ullahpara', 'Ullahpara', 'upazila', 'Bangladesh', 'sirajganj-city', 1),
  ('rangpur-thana-rangpur-kotwali', 'Rangpur Kotwali', 'thana', 'Bangladesh', 'rangpur-city', 1),
  ('mymensingh-thana-mymensingh-kotwali', 'Mymensingh Kotwali', 'thana', 'Bangladesh', 'mymensingh-city', 1),
  ('dhaka-uttara-sector-1', 'Uttara Sector 1', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-2', 'Uttara Sector 2', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-3', 'Uttara Sector 3', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-4', 'Uttara Sector 4', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-5', 'Uttara Sector 5', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-6', 'Uttara Sector 6', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-7', 'Uttara Sector 7', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-8', 'Uttara Sector 8', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-9', 'Uttara Sector 9', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-10', 'Uttara Sector 10', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-11', 'Uttara Sector 11', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-12', 'Uttara Sector 12', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-13', 'Uttara Sector 13', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-14', 'Uttara Sector 14', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-15', 'Uttara Sector 15', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-16', 'Uttara Sector 16', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-17', 'Uttara Sector 17', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-uttara-sector-18', 'Uttara Sector 18', 'subdivision', 'Bangladesh', 'dhaka-thana-uttara', 1),
  ('dhaka-mirpur-1', 'Mirpur 1', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-2', 'Mirpur 2', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-3', 'Mirpur 3', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-4', 'Mirpur 4', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-5', 'Mirpur 5', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-6', 'Mirpur 6', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-7', 'Mirpur 7', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-8', 'Mirpur 8', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-9', 'Mirpur 9', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-10', 'Mirpur 10', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-section-11', 'Section 11', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-section-12', 'Section 12', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-section-13', 'Section 13', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-section-14', 'Section 14', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('dhaka-mirpur-section-15', 'Section 15', 'area', 'Bangladesh', 'dhaka-thana-mirpur', 1),
  ('chattogram-halishahar-block-a', 'Halishahar Block A', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-b', 'Halishahar Block B', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-g', 'Halishahar Block G', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-h', 'Halishahar Block H', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-i', 'Halishahar Block I', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-j', 'Halishahar Block J', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-k', 'Halishahar Block K', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-l', 'Halishahar Block L', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1),
  ('chattogram-halishahar-block-z', 'Halishahar Block Z', 'subdivision', 'Bangladesh', 'chattogram-thana-halishahar', 1)
ON DUPLICATE KEY UPDATE
  label = VALUES(label),
  type = VALUES(type),
  country = VALUES(country),
  parentId = VALUES(parentId),
  enabled = VALUES(enabled);
