import { Link, useRoute } from "wouter";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, GraduationCap, MapPin, MessageCircle, ShieldCheck, Star, UserRound } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { trpc } from "@/lib/trpc";
import { modeLabel } from "@shared/tutors";
import { SiteContentProvider, SiteText } from "@/lib/siteContent";

export const requestThisTutorAction = { href: "/request-tutor", label: "Request this tutor" } as const;
export const publicProfileTrustContent = "This public profile shows professional information only. We keep contact details private, and phone and email are not displayed.";

function TutorProfileBody() {
  const [, params] = useRoute("/tutors/:id");
  const { data: tutor, isLoading } = trpc.tutors.byId.useQuery({ id: params?.id ?? "" }, { enabled: Boolean(params?.id) });

  if (isLoading) return <div className="site-page"><SiteHeader/><main className="shell empty-directory profile-state"><p className="eyebrow">Tutor profile</p><h1>Loading profile…</h1><p>We are fetching this tutor’s latest public information.</p></main><SiteFooter/></div>;
  if (!tutor) return <div className="site-page"><SiteHeader/><main className="shell empty-directory profile-state"><p className="eyebrow">Profile unavailable</p><h1>This tutor profile is not available.</h1><p>The profile may have been removed or the link may be outdated.</p><Link href="/tutors" className="button-primary">Back to tutor directory <ArrowLeft size={17}/></Link></main><SiteFooter/></div>;

  return <div className="site-page"><SiteHeader/><main>
    <section className="profile-hero"><div className="shell"><Link href="/tutors" className="back-link"><ArrowLeft size={16}/> Back to tutor directory</Link><div className="profile-hero-card"><div className="profile-avatar" style={{background:tutor.accent}}>{tutor.initials}</div><div className="profile-intro"><div className="profile-title-row"><div><p className="eyebrow"><SiteText slotId="public-tutor.hero.eyebrow" /></p><h1>{tutor.name}<CheckCircle2 size={20} className="verified-icon" aria-label="Verified tutor"/></h1><p>{tutor.headline}</p></div><div className="profile-actions"><Link href={requestThisTutorAction.href} className="button-primary"><MessageCircle size={17}/><SiteText slotId="public-tutor.hero.cta" fallback={requestThisTutorAction.label} /></Link><span className="profile-action-note"><SiteText slotId="public-tutor.hero.cta-note" /></span></div></div><div className="profile-facts"><span><MapPin size={16}/>{tutor.locationLabel}</span><span><GraduationCap size={16}/>{tutor.institution}</span><span><Clock3 size={16}/>{tutor.experience} years experience</span></div></div></div></div></section>
    <section className="profile-section"><div className="shell profile-layout"><div className="profile-main"><div className="profile-tabs"><a className="active" href="#personal"><SiteText slotId="public-tutor.tab.personal" /></a><a href="#education"><SiteText slotId="public-tutor.tab.education" /></a><a href="#preferences"><SiteText slotId="public-tutor.tab.preferences" /></a></div><section className="profile-content-block" id="personal"><div className="section-title"><div className="section-icon"><UserRound size={18}/></div><div><p className="eyebrow"><SiteText slotId="public-tutor.personal.eyebrow" /></p><h2><SiteText slotId="public-tutor.personal.heading" /></h2></div></div><p className="profile-about">{tutor.about}</p><div className="profile-stat-grid"><div><strong>{tutor.experience}+</strong><span>Years teaching</span></div><div><strong>{tutor.subjects.length}</strong><span>Core subjects</span></div><div><strong>{tutor.levels.length}</strong><span>Learning levels</span></div></div></section><section className="profile-content-block" id="education"><div className="section-title"><div className="section-icon"><GraduationCap size={18}/></div><div><p className="eyebrow"><SiteText slotId="public-tutor.education.eyebrow" /></p><h2><SiteText slotId="public-tutor.education.heading" /></h2></div></div><div className="education-item"><div className="education-dot"/><div><strong>{tutor.education}</strong><p>{tutor.institution}</p><span>Academic qualification</span></div></div><div className="expertise-list">{tutor.subjects.map((subject)=><span key={subject}>{subject}</span>)}</div></section><section className="profile-content-block" id="preferences"><div className="section-title"><div className="section-icon"><CalendarDays size={18}/></div><div><p className="eyebrow"><SiteText slotId="public-tutor.preferences.eyebrow" /></p><h2><SiteText slotId="public-tutor.preferences.heading" /></h2></div></div><div className="preference-grid"><div><span>Preferred mode</span><strong>{modeLabel(tutor.mode)}</strong></div><div><span>Availability</span><strong>{tutor.availability}</strong></div><div><span>Monthly expectation</span><strong>৳{tutor.fee.toLocaleString()} <small>starting from</small></strong></div><div><span>Languages</span><strong>{tutor.languages.join(" · ")}</strong></div></div></section></div><aside className="profile-aside"><div className="trust-card"><div className="trust-card-top"><ShieldCheck size={21}/><span><SiteText slotId="public-tutor.trust.title" /></span></div><h3><SiteText slotId="public-tutor.trust.heading" /></h3><p><SiteText slotId="public-tutor.trust.body" /></p><Link href={requestThisTutorAction.href} className="button-primary full-button"><SiteText slotId="public-tutor.trust.cta" /></Link></div><div className="profile-note"><Star size={17}/><div><strong><SiteText slotId="public-tutor.privacy.title" /></strong><p>{publicProfileTrustContent}</p></div></div></aside></div></section>
  </main><SiteFooter/></div>;
}

/** Public profile copy is Admin-editable; slots fall back to the code defaults. */
export default function TutorProfile() {
  return <SiteContentProvider page="tutor-profile"><TutorProfileBody /></SiteContentProvider>;
}
